name: Deploy Electron App (Windows)

on:
  push:
    tags:
      - '*'  # Il workflow parte quando viene creato un tag

jobs:
  build:
    runs-on: windows-latest  # Eseguito su Windows

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get version from tag and OS
        shell: pwsh
        run: |
          $version = $env:GITHUB_REF_NAME -replace 'v', ''   # Rimuove la "v" dal tag (es. "v1.2.3" → "1.2.3")
          $os = "windows"                                    # Aggiunge l'OS
          echo "APP_VERSION=$version-$os" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Update package.json version
        shell: pwsh
        run: |
          $packageJson = Get-Content package.json | ConvertFrom-Json
          $packageJson.version = "${{ env.APP_VERSION }}"
          $packageJson | ConvertTo-Json -Depth 10 | Set-Content package.json -Encoding utf8

      - name: Install dependencies
        run: npm ci  # Installazione pulita

      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYTOKEN }}
        run: npx electron-forge publish --verbose
