name: Deploy Electron App

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOYTOKEN }}
      run: npm run publish