name: Deploy Electron App

on:
  push:
    tags:
      - '*'  # Avvia il workflow su qualsiasi tag

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get version from tag
        run: echo "APP_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      # Questo rimuove la "v" dal tag, es. "v1.2.3" → "1.2.3"

      - name: Update package.json version
        run: |
          npm install jq -g
          jq '.version = "${{ env.APP_VERSION }}"' package.json > temp.json && mv temp.json package.json

      - name: Install dependencies
        run: npm install

      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYTOKEN }}
        run: npx electron-forge publish --verbose
